-- Create sequences for ID generation
CREATE SEQUENCE IF NOT EXISTS mock_endpoint_SEQ START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS http_config_SEQ START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS mock_response_SEQ START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS request_log_SEQ START WITH 1 INCREMENT BY 50;
